### PR TITLE
	modified:   add kzzi k68 pro keyboard support

### PR DESCRIPTION
**Pull request by XusMochizuki**
add support for kzzi-k68pro
tested read on my keyboard is ok, not testing for write.

see image below for logs
8cedc3fdf2f5de032b292225ee8bda89

### CODE REVIEW

**Review by carlossless — CHANGES_REQUESTED** [review]
@XusMochizuki thanks for the PR!

Before I merge this in, can you please add an entry with your keyboard details into README.md? - Most importantly the md5 for bootloader.

**Comment by XusMochizuki** [comment]
Is this md5 for bootloader mean the md5 value returned by using _function get_md5_from_hex ()_  with output.hex file?  If so, I just updated it.

**Comment by carlossless** [comment]
@XusMochizuki it's the md5 value when reading only the bootloader segment (use the `-b` flag - `sinowealth-kb-tool read -b ...`)

**Comment by XusMochizuki** [comment]
ok, I got an 12kb file by this command, and a MD5 value : 3e0ebd0c440af5236d7ff8872343f85d was been printed in terminal, I updated READMD.md now, check it.
{C657CDE0-F3F3-4219-8588-252933CF0593}

**Review by carlossless — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
